FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build-env
WORKDIR /app

COPY ./ShipShapeShipSensors/*.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish "ShipShapeShipSensors/ShipShapeShipSensors.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "ShipShapeShipSensors.dll"]